using System;

namespace _01_Task
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("2089 в двуична бройна система- ");             long numberN = 2089;             Console.WriteLine(Convert.ToString(numberN, 2));              Console.WriteLine("2089 в осмична бройна система-");             int numberO = 2089;             Console.WriteLine(Convert.ToString(numberO, 8 ));              Console.WriteLine("2089 в шеснадесетична бройна система-");             int numberH = 2089;             Console.WriteLine(Convert.ToString(numberH, 16));              //with loops--->              Console.Write("Въведете N(2089): ");             int n = int.Parse(Console.ReadLine());             int divider = 2;             string a = string.Empty;             for (int i = n; i != 0; i /= 2)             {                 if (i % divider == 0)                 {                     a += 0;                 }                 else if (i % divider != 0)                 {                     a += 1;                 }             }             string revstr = "";             int length;             length = a.Length - 1;                        while (length >= 0)             {                 revstr += a[length];                          length--;                                              }             Console.WriteLine("Двуична бройна система:");             Console.WriteLine(revstr);                 Console.Write("Въведете N(2089): ");             int decVal = int.Parse(Console.ReadLine());             int quot, d = 1, j;             int[] octalVal = new int[80];               quot = decVal;               while (quot != 0)             {                 octalVal[d++] = quot % 8;                 quot = quot / 8;             }              Console.WriteLine("Осмична бройна система: ");             for (j = d - 1; j > 0; j--)                 Console.Write(octalVal[j]);                 Console.Write("\nВъведете N(2089): ");             int decimalNumber = int.Parse(Console.ReadLine());             int quotient;             int k = 1, x, temp = 0;             char[] hexadecimalNumber = new char[100];             char temp1;               quotient = decimalNumber;             while (quotient != 0)             {                 temp = quotient % 16;                 if (temp < 10)                     temp = temp + 48;                 else                     temp = temp + 55;                 temp1 = Convert.ToChar(temp);                 hexadecimalNumber[k++] = temp1;                 quotient = quotient / 16;             }             Console.WriteLine("Шеснадесетична бройна система: ");             for (x = k - 1; x > 0; x--)                 Console.Write(hexadecimalNumber[x]);             Console.Read(); 
        }
    }
}
